#+STARTUP: showall
#+OPTIONS: toc:nil
#+OPTIONS: H:5
#+EXPORT_EXCLUDE_TAGS: noexport
#+title: JAIF -- programme



| 09h00 |                                            | Accueil café - badges                                                                                                           |
| 09h30 | Philippe Maurine  (LIRMM)                  | Ouverture de la journée & mot d’accueil                                                                                         |
| 09h45 |                                            | *Session 1 – Applications concrètes et implications juridiques*                                                                   |
|       | Lennert Wouters / Benedikt Gierlichs (KUL) | (tbd)                                                                                                                           |
|       | Francois Viangalli (Univ. Grenoble-Alpes)  | Les attaques par injection de fautes : premiers jalons pour une analyse juridique                                               |
| 10h45 |                                            | Pause café - [[#posters][posters / demos / stands]]                                                                                           |
| 11h30 |                                            | *Session 2 – Contremesures Logicielles*                                                                                           |
|       | Sébastien Michelland (IRISA)               | Analyse statique pour quantifier la robustesse des programmes contre les attaques multi-fautes sur le flot de contrôle          |
|       | Yanis Sellami (CEA)                        | Vérification efficace des protections contre les attaques par injection de fautes au niveau binaire                             |
|       | Etienne Boespflug (Verimag)                | Étude de la surface d'attaque de Rust face aux injections de fautes multiples                                                   |
| 12h30 |                                            | Déjeuner - [[#posters][posters and demos]]                                                                                                    |
| 14h00 |                                            | *Session 3 – PQC, Vérification formelle et caractérisation*                                                                       |
|       | Anderson Callé Viera (Thales)              | (tbd)                                                                                                                           |
|       | Thomas Techer (SGS)                        | Quand la cryptographie post-quantique rencontre l'injection de fautes : attaques pratiques contre ML-KEM et ML-DSA.             |
|       | Daniel Thirion (STM)                       | Vérification formelle guidée par des modèles de fautes de primitives cryptographiques matérielles contre les attaques en fautes |
|       | Jonah Alle Monne (CEA)                     | Synthèse de programmes de caractérisation à partir du RTL pour l'injection de fautes                                            |
| 15h30 |                                            | Pause café - [[#posters][posters and demos]]                                                                                                  |
| 16h15 |                                            | *Session 4 – Laser & photoémission*                                                                                               |
|       | Rodrigo Silva Lima (AlphaNov)              | Analyse de l’efficacité des lasers pico et femto seconde à l’injection de faute.                                                |
|       | Mael Coatanhay (IETR)                      | Photoémission et injection de fautes laser sur microcontrôleur RISC-V                                                           |
|       | Olivier Savry (CEA)                        | Au-delà de la redondance : polymorphisme matériel contre l'injection de fautes par laser multi-faisceaux                        |
| 17h15 | Comité d’organisation                      | Mot de clôture de la journée                                                                                                    |
| 19h00 |                                            | [[./infos-pratiques.html#social-event][social event]]                                                                                                                    |


*Posters*

| Germain Eguina (LCIS) et al. | [[#eguina][Évaluation et renforcement des modules d'IA embarquée pour la sûreté et la sécurité dans les systèmes critiques]] |

Mouad Rabiai, Valentin Egloff, Vincent Beroulle, Paolo Maistri Modélisation des fautes
au niveau RTL et contre-mesures : axes de recherche dans le contexte des attaques
laser sur les microarchitectures RISC-V
(Univ. Grenoble Alpes)

Telly Raheriniaina, Kévin Quénéhervé, Philippe Tanguy, Rachid Dafali, Vianney Lapôtre.
Rejeu d'instructions piloté par le matériel dans le coeur RISC-V cva6
(Univ. Bretagne Sud, DGA MI)

Boenzemwendé, Israel Kafando, Jonah Alle Monne, Damien Couroussé, Mathieu Jan
Une méthodologie pour analyser le comportement de la microarchitecture sous
injection de glitches d'horloge. (Univ. Grenoble Alpe, CEA, Univ. Paris-Saclay)

Laurent Maingault, Stéphanie Anceau, Alejandro Urena-Acuna, Guillaume hubert,
Sophie Bouat, Rémi Tucoulou. Attaque par injection de fautes aux rayons X sur un
transistor unique en 22 nm FD-SOI. (CEA, ONERA, SIMaP, ESRF)

Hugo Perrin, Raphael Viera, Jean baptiste Rigaud. Stimulation thermique par laser
des capteurs de courant intégrés dans les dispositifs silicium. (ENSME)

** Présentations invitées

to be detailed

** Présentations
:PROPERTIES:
:CUSTOM_ID: presentations
:END:


to be detailed

** Posters
:PROPERTIES:
:CUSTOM_ID: posters
:END:

*** Évaluation et renforcement des modules d'IA embarqués pour les systèmes critiques
:PROPERTIES:
:CUSTOM_ID: eguina
:END:

  *Germain EGUINA* (LCIS, Grenoble INP-UGA),
  Vincent BEROULLE (LCIS, Grenoble INP-UGA),
  Valentin EGLOFF (LCIS, Grenoble INP-UGA),
  Louis MORGE-ROLLET (LCIS, Grenoble INP-UGA),
  Youssef SERRESTOU (LAUM, Université du Mans - CNRS UMR 6613)

*Abstract*.
Ces dernières années, le déploiement de l'IA migre des serveurs vers la périphérie dans les systèmes critiques. Utiliser les modèles au plus près des données réduit la dépendance aux serveurs et permet une prise de décision en temps réel. Cette approche réduit la latence, la consommation de bande passante et les coûts opérationnels tout en améliorant la fiabilité et la confidentialité des données. Cependant, elle augmente la surface d'attaque et l'exposition aux perturbations matérielles et environnementales. Contrairement aux serveurs, les systèmes en périphérie sont accessibles physiquement et fonctionnent dans des environnements imprévisibles les rendant ainsi vulnérables aux menaces algorithmiques et matérielles. Dans les systèmes critiques, cette exposition doit être prise en compte pour garantir leur sécurité et leur sûreté.

Notre travail porte sur les perturbations intentionnelles et non intentionnelles (attaques et fautes) modifiant la sortie des réseaux de neurones convolutifs largement utilisés dans les tâches de perception et de classification (reconnaissance d'image, détection d'objets, classification de signaux) au cœur de nombreux systèmes critiques. Ces perturbations peuvent atteindre les modèles par leurs entrées (exploitation algorithmique) ou via le matériel (injection de fautes). Nous évaluerons leur capacité à fonctionner correctement en présence de telles perturbations, leur robustesse.

L'objectif est de développer une méthodologie d'évaluation des modèles unifiée prenant en compte simultanément les vecteurs algorithmiques et matériels. Un tel environnement fera le pont entre les communautés de la sécurité et de la sûreté, offrant une évaluation réaliste des vulnérabilités. Nous proposerons ensuite des techniques pour améliorer leur robustesse face à ces perturbations.

*Bio*.
Doctorant depuis février 2026 au Laboratoire de Conception et d'Intégration des Systèmes (LCIS) à Valence. Diplômé en 2025 de l'ENSPIMA (Bordeaux INP), où j'ai suivi une formation d'ingénieur en maintenance aéronautique avec une spécialisation en systèmes avioniques et embarqués. Mes travaux de recherche portent sur l'évaluation et le renforcement de la robustesse des modules d'IA embarqués dans les systèmes critiques face aux perturbations intentionnelles et non intentionnelles en considérant conjointement les dimensions algorithmique et matérielle.
